services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: litebank
      POSTGRES_PASSWORD: litebank
      POSTGRES_DB: litebank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: litebank-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
