name: Deploy LiteBank to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alembic psycopg2-binary  # Ensure DB migration tools are available

      # Set environment variables from GitHub secrets
      - name: Set environment variables
        run: |
          echo "RENDER_DATABASE_URL=${{ secrets.RENDER_DATABASE_URL }}" >> $GITHUB_ENV

      # Run database migrations
      - name: Run Alembic migrations
        run: |
          alembic upgrade head
        env:
          DATABASE_URL: ${{ secrets.RENDER_DATABASE_URL }}

      # Deploy to Render
      - name: Deploy to Render
        uses: render-examples/deploy-action@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
